name: s3-deployment
on:
  push:
    branches:
      - "main"
      - "master"
      - "research"
jobs:
  deploy:
    name: Deploy /build to S3 bucket
    runs-on: ubuntu-latest
    environment: production
    env:
      REACT_APP_VERSION: ${{ github.sha }}
      REACT_APP_API_URL: ${{ secrets.TELEMETRY_API }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_SECRET_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Updload results of /build to S3
        run: aws s3 sync ./build ${{ secrets.S3_BUCKET_URI }}
      - name: Updload results of /build to S3
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
